spring:
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  devtools:
    livereload:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        batch_size: 50
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   local
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#   prod
    url: jdbc:mysql://api-stack-prod-database-uft7lg447cbp.czmi06oc4ahh.ap-southeast-1.rds.amazonaws.com:3306/athenadb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  data:
    mongodb:
      uri: mongodb+srv://leo09613257:leo77777@clustercustom.aabfy.mongodb.net/clusterCustom?retryWrites=true&w=majority&appName=clusterCustom

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 10
  shutdown: "graceful"

management:
  endpoints:
    web:
      exposure:
        include: health    # 只開放 health endpoint
      base-path: /actuator # 設置基礎路徑
  endpoint:
    health:
      show-details: always # 顯示詳細的健康檢查信息