spring:
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  devtools:
    livereload:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        batch_size: 50
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  data:
    mongodb:
      uri: mongodb+srv://leo09613257:leo77777@clustercustom.aabfy.mongodb.net/clusterCustom?retryWrites=true&w=majority&appName=clusterCustom

server:
  port: 8090
  compression:
    enabled: true
    min-response-size: 10
  shutdown: "graceful"